version: "3.8"

services:

  web:
    image: nginx:latest
    container_name: wwwraven
    ports:
      - "4080:80"
    volumes:
      - /srv/rvnprofile/logs:/usr/share/nginx/html
      - ./wwwraven/server.conf:/etc/nginx/conf.d/default.conf
      - ./wwwraven/nginx.conf:/etc/nginx/nginx.conf

  main:
    build: ravenports
    container_name: ravenports
    privileged: true
    volumes:
      - /srv/rvnprofile:/var/ravenports/primary
      - /srv/specs:/var/ravenports/specs
      - /srv/ccache-raven:/var/cache/ccache
      - /srv/cache-rvn:/var/cache/rvn
